// Product Data - Based on MadhuraM By HHM Menu (Complete Menu from scanmenu.in)
// Products organized by category as in the original menu

export const products = [
  // ==================== CATEGORY: DAIRY (डेयरी) ====================
  {
    id: 1,
    name: "Dahi",
    nameHindi: "दही",
    price: 120,
    weight: "1kg",
    category: "dairy",
    image: "/products/menu/dahi.jpg",
    description: "Fresh dahi, creamy and smooth. Made from pure milk with live cultures. Perfect for rituals and daily consumption.",
    ingredients: "Pure milk, Live cultures",
    shelfLife: "2 days",
    badge: "Fresh",
    badgeType: "fresh",
    rating: 4.8,
    reviews: 94,
  },
  {
    id: 2,
    name: "Khowa (Mawa)",
    nameHindi: "खोया (मावा)",
    price: 400,
    weight: "1kg",
    category: "dairy",
    image: "/products/menu/khowa.jpg",
    description: "Sweet khoya, rich and decadent. Made by slow cooking milk for hours. Essential for making traditional sweets at home.",
    ingredients: "100% Pure milk",
    shelfLife: "7 days",
    badge: "Pure",
    badgeType: "pure",
    rating: 4.8,
    reviews: 98,
  },
  {
    id: 3,
    name: "Paneer",
    nameHindi: "पनीर",
    price: 350,
    weight: "1kg",
    category: "dairy",
    image: "/products/menu/paneer.jpg",
    description: "Pure N Sure - Soft and fresh paneer made from pure milk. Perfect for curries and snacks.",
    ingredients: "Pure milk, Lemon juice",
    shelfLife: "2 days",
    badge: "Fresh Today",
    badgeType: "fresh",
    rating: 4.8,
    reviews: 112,
  },

  // ==================== CATEGORY: FEATURED - MAHAPRASAD (महाप्रसाद) ====================
  {
    id: 4,
    name: "Peda Mahaprasad",
    nameHindi: "पेड़ा महाप्रसाद",
    price: 400,
    weight: "1kg",
    category: "featured",
    image: "/products/menu/peda-mahaprasad.png",
    description: "Sweet peda, melt in your mouth. The sacred offering from Jyotirling Baba Baidyanath Dham. Made with pure desi ghee and love.",
    ingredients: "Khoya, Desi ghee, Sugar, Cardamom, Saffron",
    shelfLife: "7 days",
    badge: "महाप्रसाद",
    badgeType: "divine",
    rating: 5.0,
    reviews: 156,
    isFeatured: true,
    isSpecial: true,
  },

  // ==================== CATEGORY: SWEETS (मिठाई) ====================
  {
    id: 5,
    name: "Rasgulla",
    nameHindi: "रसगुल्ला",
    price: 10,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/rasgulla.jpg",
    description: "Spongy rasgulla, yummy. Soft and spongy balls soaked in pure sugar syrup. Fresh made daily.",
    ingredients: "Fresh chhena, Sugar, Rose water, Cardamom",
    shelfLife: "3 days",
    badge: "Popular",
    badgeType: "popular",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 6,
    name: "Gulab Jamun",
    nameHindi: "गुलाब जामुन",
    price: 10,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/gulab-jamun.jpg",
    description: "Sweet gulab jamun, soft and juicy. Classic sweet made with khoya, soaked in rose-flavored sugar syrup.",
    ingredients: "Khoya, Maida, Sugar, Rose water, Cardamom",
    shelfLife: "5 days",
    badge: "Classic",
    badgeType: "traditional",
    rating: 4.7,
    reviews: 72,
  },
  {
    id: 7,
    name: "Jalebi",
    nameHindi: "जलेबी",
    price: 10,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/jalebi.jpg",
    description: "Crispy jalebi, syrupy sweet. Crispy, spiral-shaped sweet soaked in saffron-flavored sugar syrup. Best served hot.",
    ingredients: "Maida, Curd, Sugar, Saffron, Ghee",
    shelfLife: "2 days",
    badge: "Hot & Fresh",
    badgeType: "popular",
    rating: 4.5,
    reviews: 56,
  },
  {
    id: 8,
    name: "Doda Barfi",
    nameHindi: "दोदा बर्फी",
    price: 500,
    weight: "1kg",
    category: "sweets",
    image: "/products/menu/doda-barfi.jpg",
    description: "Doda barfi, rich and tasty. Rich and fudgy doda barfi with nuts. A specialty from Deoghar.",
    ingredients: "Milk, Sugar, Nuts, Ghee",
    shelfLife: "7 days",
    badge: "Special",
    badgeType: "divine",
    rating: 5.0,
    reviews: 134,
    isSpecial: true,
  },
  {
    id: 9,
    name: "Raj Bhog",
    nameHindi: "राज भोग",
    price: 20,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/raj-bhog.jpg",
    description: "Raj bhog, delicious sweet. Royal Bengali sweet - larger rasgulla with saffron and dry fruit filling.",
    ingredients: "Chhena, Saffron, Dry fruits, Sugar",
    shelfLife: "3 days",
    badge: "Royal",
    badgeType: "premium",
    rating: 4.9,
    reviews: 89,
  },
  {
    id: 10,
    name: "Kaju Barfi",
    nameHindi: "काजू बर्फी",
    price: 950,
    weight: "1kg",
    category: "sweets",
    image: "/products/menu/kaju-barfi.jpg",
    description: "Premium cashew delight - Mouth-melting Kaju Barfi. Premium cashew barfi with silver vark, made with 100% pure cashews and desi ghee.",
    ingredients: "Cashew nuts, Desi ghee, Sugar, Silver vark",
    shelfLife: "10 days",
    badge: "Premium",
    badgeType: "premium",
    rating: 4.9,
    reviews: 142,
    isFeatured: true,
    isSpecial: true,
  },
  {
    id: 11,
    name: "Milk Cake",
    nameHindi: "मिल्क केक",
    price: 500,
    weight: "1kg",
    category: "sweets",
    image: "/products/menu/milk-cake.jpg",
    description: "Soft milk cake, yummy. Delicious milk cake with caramelized flavor. A traditional favorite.",
    ingredients: "Milk, Sugar, Ghee, Cardamom",
    shelfLife: "7 days",
    badge: "Popular",
    badgeType: "popular",
    rating: 4.8,
    reviews: 56,
  },
  {
    id: 12,
    name: "Motichur Ladoo",
    nameHindi: "मोतीचूर लड्डू",
    price: 180,
    weight: "500g",
    category: "sweets",
    image: "/products/menu/motichur-ladoo.jpg",
    description: "Classic motichur ladoo made with pure desi ghee. Perfect for celebrations and temple offerings.",
    ingredients: "Besan, Desi ghee, Sugar, Cardamom",
    shelfLife: "7 days",
    badge: "Traditional",
    badgeType: "traditional",
    rating: 4.7,
    reviews: 45,
  },
  {
    id: 13,
    name: "Besan Ladoo",
    nameHindi: "बेसन लड्डू",
    price: 180,
    weight: "500g",
    category: "sweets",
    image: "/products/menu/besan-ladoo.jpg",
    description: "Nutritious besan ladoo with rich ghee flavor. A healthy sweet treat for all occasions.",
    ingredients: "Besan, Desi ghee, Sugar, Cardamom",
    shelfLife: "10 days",
    badge: "Healthy",
    badgeType: "fresh",
    rating: 4.6,
    reviews: 67,
  },
  {
    id: 14,
    name: "Ghee Ladoo",
    nameHindi: "घी के लड्डू",
    price: 400,
    weight: "1kg",
    category: "sweets",
    image: "/products/menu/ghee-ladoo.jpg",
    description: "Rich and aromatic ghee ladoo. Made with premium desi ghee. Perfect for festivals.",
    ingredients: "Atta, Desi ghee, Sugar, Cardamom",
    shelfLife: "10 days",
    badge: "Rich",
    badgeType: "premium",
    rating: 4.8,
    reviews: 89,
  },
  {
    id: 15,
    name: "Gondh Ladoo",
    nameHindi: "गोंध के लड्डू",
    price: 500,
    weight: "1kg",
    category: "sweets",
    image: "/products/menu/gondh-ladoo.jpg",
    description: "Nutritious gondh ladoo with dry fruits. Perfect for winter and new mothers. Rich in nutrients.",
    ingredients: "Gondh, Desi ghee, Dry fruits, Jaggery",
    shelfLife: "15 days",
    badge: "Nutritious",
    badgeType: "traditional",
    rating: 4.7,
    reviews: 45,
  },
  {
    id: 16,
    name: "Khowa Tikki",
    nameHindi: "खोया टिक्की",
    price: 15,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/khowa-tikki.jpg",
    description: "Delicious khowa tikki, rich and sweet. Made with pure khoya and garnished with nuts.",
    ingredients: "Khoya, Sugar, Nuts, Cardamom",
    shelfLife: "7 days",
    badge: "Special",
    badgeType: "traditional",
    rating: 4.6,
    reviews: 34,
  },
  {
    id: 17,
    name: "RasRaj",
    nameHindi: "रसराज",
    price: 20,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/rasraj.jpg",
    description: "Sweet rasraj, a delightful treat. Similar to rasgulla but with a richer texture and taste.",
    ingredients: "Chhena, Sugar, Saffron, Cardamom",
    shelfLife: "3 days",
    badge: "Delicious",
    badgeType: "popular",
    rating: 4.7,
    reviews: 56,
  },
  {
    id: 18,
    name: "Allahabadi Barfi",
    nameHindi: "इलाहाबादी बर्फी",
    price: 15,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/allahabadi-barfi.jpg",
    description: "Special Allahabadi barfi with unique taste. A regional specialty with rich flavor.",
    ingredients: "Khoya, Sugar, Ghee, Cardamom",
    shelfLife: "7 days",
    badge: "Regional Special",
    badgeType: "traditional",
    rating: 4.6,
    reviews: 28,
  },
  {
    id: 19,
    name: "Sondesh",
    nameHindi: "संदेश",
    price: 500,
    weight: "1kg",
    category: "sweets",
    image: "/products/menu/sondesh.jpg",
    description: "Classic Bengali sondesh made with fresh chhena. Light and delicious.",
    ingredients: "Fresh chhena, Sugar, Cardamom",
    shelfLife: "3 days",
    badge: "Bengali Special",
    badgeType: "traditional",
    rating: 4.6,
    reviews: 78,
  },
  {
    id: 20,
    name: "Papaya Ladoo",
    nameHindi: "पपीता लड्डू",
    price: 20,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/papaya-ladoo.png",
    description: "Unique and delicious papaya ladoo. A healthy twist to traditional sweets.",
    ingredients: "Papaya, Coconut, Sugar, Cardamom",
    shelfLife: "7 days",
    badge: "Unique",
    badgeType: "fresh",
    rating: 4.5,
    reviews: 23,
  },
  {
    id: 21,
    name: "Nariyal Ladoo",
    nameHindi: "नारियल लड्डू",
    price: 20,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/nariyal-ladoo.png",
    description: "Delicious coconut ladoo made with fresh coconut and condensed milk.",
    ingredients: "Fresh coconut, Condensed milk, Sugar, Cardamom",
    shelfLife: "7 days",
    badge: "Fresh",
    badgeType: "fresh",
    rating: 4.8,
    reviews: 94,
  },
  {
    id: 22,
    name: "Dry Fruit Ladoo",
    nameHindi: "ड्राई फ्रूट लड्डू",
    price: 20,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/dryfruit-ladoo.png",
    description: "Premium dry fruit ladoo made with cashews, almonds, and pistachios. Rich and nutritious.",
    ingredients: "Cashews, Almonds, Raisins, Pistachios, Jaggery",
    shelfLife: "10 days",
    badge: "Premium",
    badgeType: "premium",
    rating: 5.0,
    reviews: 112,
  },
  {
    id: 23,
    name: "Pumpkin Ladoo",
    nameHindi: "कद्दू लड्डू",
    price: 20,
    weight: "pc",
    category: "sweets",
    image: "/products/menu/motichur-ladoo.jpg",
    description: "Unique pumpkin ladoo with subtle sweetness. A healthy and different sweet option.",
    ingredients: "Pumpkin, Sugar, Ghee, Cardamom",
    shelfLife: "7 days",
    badge: "Unique",
    badgeType: "fresh",
    rating: 4.4,
    reviews: 18,
  },

  // ==================== CATEGORY: HONEY & GHEE (शहद और घी) ====================
  {
    id: 24,
    name: "Pure Honey",
    nameHindi: "शुद्ध शहद",
    price: 185,
    weight: "250g",
    category: "honey",
    image: "/products/menu/honey.jpg",
    description: "Pure organic honey from our own garden, naturally harvested without processing.",
    ingredients: "100% Pure Organic Honey",
    shelfLife: "12 months",
    badge: "Organic",
    badgeType: "organic",
    rating: 4.8,
    reviews: 56,
  },
  {
    id: 25,
    name: "Ghar ka Shuddh Ghee",
    nameHindi: "घर का शुद्ध घी",
    price: 1135,
    weight: "1kg",
    category: "ghee",
    image: "/products/ghee.png",
    description: "Pure desi ghee prepared using traditional Bilona method from A2 cow milk.",
    ingredients: "100% Pure A2 Cow Milk",
    shelfLife: "6 months",
    badge: "Bilona Method",
    badgeType: "pure",
    rating: 4.9,
    reviews: 89,
  },

  // ==================== CATEGORY: SNACKS (नाश्ता) ====================
  {
    id: 26,
    name: "Samosa with Chutney",
    nameHindi: "समोसा चटनी के साथ",
    price: 10,
    weight: "pc",
    category: "snacks",
    image: "/products/menu/samosa.jpg",
    description: "Crispy samosa served with tangy tamarind chutney. Perfect evening snack.",
    ingredients: "Maida, Potatoes, Spices, Oil",
    shelfLife: "Same day",
    badge: "Hot",
    badgeType: "fresh",
    rating: 4.7,
    reviews: 134,
  },
  {
    id: 27,
    name: "Subah ka Nashta",
    nameHindi: "सुबह का नाश्ता",
    price: 30,
    weight: "3pc",
    category: "snacks",
    image: "/products/menu/kachori.jpg",
    description: "Traditional breakfast - Hing Kachori with Sabji. Start your day the Deoghar way!",
    ingredients: "Maida, Urad dal, Spices, Potatoes",
    shelfLife: "Same day",
    badge: "Breakfast",
    badgeType: "traditional",
    rating: 4.8,
    reviews: 89,
  },
  {
    id: 28,
    name: "Punjabi Mathri Plain",
    nameHindi: "पंजाबी मठरी",
    price: 10,
    weight: "5pc",
    category: "snacks",
    image: "/products/namkeen.png",
    description: "Crispy punjabi mathri. Perfect with tea or as a travel snack.",
    ingredients: "Maida, Ajwain, Salt, Oil",
    shelfLife: "15 days",
    badge: "Crunchy",
    badgeType: "fresh",
    rating: 4.5,
    reviews: 56,
  },

  // ==================== CATEGORY: BEVERAGES (पेय पदार्थ) ====================
  // Cold Drinks
  {
    id: 29,
    name: "ThumpsUp 750ml",
    nameHindi: "थम्सअप 750ml",
    price: 45,
    weight: "750ml",
    category: "beverages",
    image: "/products/menu/thumbsup.jpg",
    description: "Refreshing ThumpsUp - the original cola taste.",
    ingredients: "Carbonated water, Sugar, Flavorings",
    shelfLife: "6 months",
    badge: "Cold Drink",
    badgeType: "popular",
    rating: 4.6,
    reviews: 45,
  },
  {
    id: 30,
    name: "Coca-Cola",
    nameHindi: "कोका-कोला",
    price: 45,
    weight: "750ml",
    category: "beverages",
    image: "/products/menu/coca-cola.jpg",
    description: "Classic Coca-Cola - refreshing taste for all occasions.",
    ingredients: "Carbonated water, Sugar, Flavorings",
    shelfLife: "6 months",
    badge: "Classic",
    badgeType: "popular",
    rating: 4.7,
    reviews: 56,
  },
  {
    id: 31,
    name: "Monster Energy Drink",
    nameHindi: "मॉन्स्टर एनर्जी ड्रिंक",
    price: 125,
    weight: "350ml",
    category: "beverages",
    image: "/products/menu/thumbsup.jpg",
    description: "Monster Energy Drink for instant energy boost.",
    ingredients: "Carbonated water, Taurine, Caffeine, B-vitamins",
    shelfLife: "12 months",
    badge: "Energy",
    badgeType: "premium",
    rating: 4.5,
    reviews: 34,
  },
  {
    id: 32,
    name: "Sprite",
    nameHindi: "स्प्राइट",
    price: 40,
    weight: "750ml",
    category: "beverages",
    image: "/products/menu/sprite.jpg",
    description: "Refreshing lemon-lime flavored clear soda.",
    ingredients: "Carbonated water, Sugar, Lemon-lime flavor",
    shelfLife: "6 months",
    badge: "Refreshing",
    badgeType: "fresh",
    rating: 4.6,
    reviews: 38,
  },
  {
    id: 33,
    name: "Mazza",
    nameHindi: "माज़ा",
    price: 45,
    weight: "600ml",
    category: "beverages",
    image: "/products/menu/mazza.jpg",
    description: "Mango drink - the national drink of India.",
    ingredients: "Water, Mango pulp, Sugar",
    shelfLife: "6 months",
    badge: "Mango",
    badgeType: "popular",
    rating: 4.7,
    reviews: 67,
  },
  {
    id: 34,
    name: "Kinley Water",
    nameHindi: "किन्ले पानी",
    price: 20,
    weight: "1L",
    category: "beverages",
    image: "/products/menu/tata-juice.png",
    description: "Pure and safe packaged drinking water.",
    ingredients: "Purified water",
    shelfLife: "6 months",
    badge: "Pure",
    badgeType: "pure",
    rating: 4.5,
    reviews: 23,
  },
  {
    id: 35,
    name: "Maaza Tetra Pack",
    nameHindi: "माज़ा टेट्रा पैक",
    price: 10,
    weight: "135ml",
    category: "beverages",
    image: "/products/menu/maaza-tetra.jpg",
    description: "Mango drink in convenient tetra pack.",
    ingredients: "Water, Mango pulp, Sugar",
    shelfLife: "6 months",
    badge: "Mango",
    badgeType: "popular",
    rating: 4.6,
    reviews: 34,
  },

  // Tata Juices
  {
    id: 36,
    name: "Tata Water",
    nameHindi: "टाटा पानी",
    price: 20,
    weight: "200ml",
    category: "beverages",
    image: "/products/menu/tata-juice.png",
    description: "Pure and refreshing Tata drinking water.",
    ingredients: "Purified water",
    shelfLife: "6 months",
    badge: "Pure",
    badgeType: "pure",
    rating: 4.5,
    reviews: 18,
  },
  {
    id: 37,
    name: "Tata Juice Lemon",
    nameHindi: "टाटा नींबू जूस",
    price: 10,
    weight: "200ml",
    category: "beverages",
    image: "/products/menu/tata-juice.png",
    description: "Refreshing lemon juice by Tata.",
    ingredients: "Water, Lemon juice, Sugar",
    shelfLife: "6 months",
    badge: "Fresh",
    badgeType: "fresh",
    rating: 4.4,
    reviews: 15,
  },
  {
    id: 38,
    name: "Tata Juice Lichi",
    nameHindi: "टाटा लीची जूस",
    price: 10,
    weight: "200ml",
    category: "beverages",
    image: "/products/menu/tata-juice.png",
    description: "Refreshing lichi juice by Tata.",
    ingredients: "Water, Lichi pulp, Sugar",
    shelfLife: "6 months",
    badge: "Fresh",
    badgeType: "fresh",
    rating: 4.5,
    reviews: 19,
  },
  {
    id: 39,
    name: "Tata Juice Orange",
    nameHindi: "टाटा संतरा जूस",
    price: 10,
    weight: "200ml",
    category: "beverages",
    image: "/products/menu/tata-juice.png",
    description: "Refreshing orange juice by Tata.",
    ingredients: "Water, Orange juice, Sugar",
    shelfLife: "6 months",
    badge: "Fresh",
    badgeType: "fresh",
    rating: 4.4,
    reviews: 16,
  },
  {
    id: 40,
    name: "Tata Juice Mix",
    nameHindi: "टाटा मिक्स जूस",
    price: 10,
    weight: "200ml",
    category: "beverages",
    image: "/products/menu/tata-juice.png",
    description: "Refreshing mixed fruit juice by Tata.",
    ingredients: "Water, Mixed fruit juices, Sugar",
    shelfLife: "6 months",
    badge: "Fresh",
    badgeType: "fresh",
    rating: 4.5,
    reviews: 21,
  },

  // Paper Boat
  {
    id: 41,
    name: "Paper Boat Aam Panna",
    nameHindi: "पेपर बोट आम पन्ना",
    price: 20,
    weight: "250ml",
    category: "beverages",
    image: "/products/menu/paperboat.jpg",
    description: "Traditional raw mango drink with a modern twist.",
    ingredients: "Water, Raw mango, Spices, Sugar",
    shelfLife: "6 months",
    badge: "Traditional",
    badgeType: "traditional",
    rating: 4.6,
    reviews: 28,
  },
  {
    id: 42,
    name: "Paper Boat Mixed Fruit",
    nameHindi: "पेपर बोट मिक्स्ड फ्रूट",
    price: 20,
    weight: "250ml",
    category: "beverages",
    image: "/products/menu/paperboat.jpg",
    description: "Refreshing mixed fruit juice drink.",
    ingredients: "Water, Mixed fruit juices, Sugar",
    shelfLife: "6 months",
    badge: "Fresh",
    badgeType: "fresh",
    rating: 4.5,
    reviews: 22,
  },
  {
    id: 43,
    name: "Paper Boat Coconut Water",
    nameHindi: "पेपर बोट नारियल पानी",
    price: 20,
    weight: "250ml",
    category: "beverages",
    image: "/products/menu/paperboat.jpg",
    description: "Pure and refreshing coconut water.",
    ingredients: "Coconut water",
    shelfLife: "6 months",
    badge: "Natural",
    badgeType: "organic",
    rating: 4.7,
    reviews: 31,
  },
  {
    id: 44,
    name: "Paper Boat AamRas",
    nameHindi: "पेपर बोट आमरस",
    price: 20,
    weight: "250ml",
    category: "beverages",
    image: "/products/menu/paperboat.jpg",
    description: "Sweet and thick mango pulp drink.",
    ingredients: "Mango pulp, Water, Sugar",
    shelfLife: "6 months",
    badge: "Mango",
    badgeType: "popular",
    rating: 4.7,
    reviews: 35,
  },

  // ==================== CATEGORY: ICE CREAMS (आइसक्रीम) ====================
  {
    id: 45,
    name: "Amul Cup Strawberry",
    nameHindi: "अमूल कप स्ट्रॉबेरी",
    price: 10,
    weight: "55ml",
    category: "icecream",
    image: "/products/menu/amul-icecream.png",
    description: "Delicious strawberry ice cream cup by Amul.",
    ingredients: "Milk, Sugar, Strawberry, Stabilizers",
    shelfLife: "12 months",
    badge: "Ice Cream",
    badgeType: "popular",
    rating: 4.5,
    reviews: 28,
  },
  {
    id: 46,
    name: "Amul Cup Vanilla",
    nameHindi: "अमूल कप वेनिला",
    price: 10,
    weight: "55ml",
    category: "icecream",
    image: "/products/menu/amul-icecream.png",
    description: "Classic vanilla ice cream cup by Amul.",
    ingredients: "Milk, Sugar, Vanilla, Stabilizers",
    shelfLife: "12 months",
    badge: "Classic",
    badgeType: "traditional",
    rating: 4.5,
    reviews: 32,
  },
  {
    id: 47,
    name: "Amul Jumbo Cup Ch. Brownie",
    nameHindi: "अमूल जंबो कप ब्राउनी",
    price: 35,
    weight: "125ml",
    category: "icecream",
    image: "/products/menu/amul-icecream.png",
    description: "Chocolate brownie ice cream - rich and indulgent.",
    ingredients: "Milk, Sugar, Chocolate, Brownie pieces",
    shelfLife: "12 months",
    badge: "Premium",
    badgeType: "premium",
    rating: 4.7,
    reviews: 45,
  },
  {
    id: 48,
    name: "Amul Stk Kulfi Punjabi",
    nameHindi: "अमूल स्टिक कुल्फी पंजाबी",
    price: 25,
    weight: "60ml",
    category: "icecream",
    image: "/products/menu/amul-kulfi.jpg",
    description: "Traditional Punjabi kulfi on a stick.",
    ingredients: "Milk, Sugar, Pistachio, Cardamom",
    shelfLife: "12 months",
    badge: "Traditional",
    badgeType: "traditional",
    rating: 4.8,
    reviews: 56,
  },
  {
    id: 49,
    name: "Amul Stk Rabdi Rural",
    nameHindi: "अमूल स्टिक रबड़ी",
    price: 10,
    weight: "45ml",
    category: "icecream",
    image: "/products/menu/amul-kulfi.jpg",
    description: "Traditional rabdi flavored ice cream stick.",
    ingredients: "Milk, Sugar, Rabdi flavor",
    shelfLife: "12 months",
    badge: "Traditional",
    badgeType: "traditional",
    rating: 4.6,
    reviews: 28,
  },
  {
    id: 50,
    name: "Amul Stk Kulfi Rajasthani",
    nameHindi: "अमूल स्टिक कुल्फी राजस्थानी",
    price: 20,
    weight: "60ml",
    category: "icecream",
    image: "/products/menu/amul-kulfi.jpg",
    description: "Traditional Rajasthani kulfi on a stick.",
    ingredients: "Milk, Sugar, Saffron, Cardamom",
    shelfLife: "12 months",
    badge: "Traditional",
    badgeType: "traditional",
    rating: 4.7,
    reviews: 34,
  },
  {
    id: 51,
    name: "Amul Stk Kulfi Rajwadi",
    nameHindi: "अमूल स्टिक कुल्फी राजवाड़ी",
    price: 10,
    weight: "40ml",
    category: "icecream",
    image: "/products/menu/amul-kulfi.jpg",
    description: "Royal kulfi with rich taste on a stick.",
    ingredients: "Milk, Sugar, Dry fruits, Saffron",
    shelfLife: "12 months",
    badge: "Royal",
    badgeType: "premium",
    rating: 4.6,
    reviews: 29,
  },
  {
    id: 52,
    name: "Amul Tricone Chocolate",
    nameHindi: "अमूल ट्राइकोन चॉकलेट",
    price: 30,
    weight: "100ml",
    category: "icecream",
    image: "/products/menu/amul-cone.jpg",
    description: "Chocolate ice cream in crispy cone.",
    ingredients: "Milk, Sugar, Chocolate, Wafer cone",
    shelfLife: "12 months",
    badge: "Chocolate",
    badgeType: "popular",
    rating: 4.6,
    reviews: 42,
  },
  {
    id: 53,
    name: "Amul Tricone Gold BScotch",
    nameHindi: "अमूल ट्राइकोन बटर स्कॉच",
    price: 40,
    weight: "120ml",
    category: "icecream",
    image: "/products/menu/amul-cone.jpg",
    description: "Premium butterscotch ice cream in crispy cone.",
    ingredients: "Milk, Sugar, Butterscotch, Wafer cone",
    shelfLife: "12 months",
    badge: "Premium",
    badgeType: "premium",
    rating: 4.7,
    reviews: 38,
  },
  {
    id: 54,
    name: "Amul Tricone Vanilla",
    nameHindi: "अमूल ट्राइकोन वेनिला",
    price: 10,
    weight: "40ml",
    category: "icecream",
    image: "/products/menu/amul-cone.jpg",
    description: "Classic vanilla ice cream in crispy cone.",
    ingredients: "Milk, Sugar, Vanilla, Wafer cone",
    shelfLife: "12 months",
    badge: "Classic",
    badgeType: "traditional",
    rating: 4.5,
    reviews: 31,
  },
  {
    id: 55,
    name: "Amul Cup Fundoo",
    nameHindi: "अमूल कप फंडू",
    price: 15,
    weight: "60ml",
    category: "icecream",
    image: "/products/menu/amul-icecream.png",
    description: "Fun flavored ice cream cup for kids.",
    ingredients: "Milk, Sugar, Colors, Flavors",
    shelfLife: "12 months",
    badge: "Fun",
    badgeType: "popular",
    rating: 4.4,
    reviews: 25,
  },
];

// Categories organized as in the original menu
export const categories = [
  { id: "all", name: "सभी", nameEn: "All Items" },
  { id: "featured", name: "महाप्रसाद", nameEn: "Mahaprasad" },
  { id: "dairy", name: "डेयरी", nameEn: "Dairy Products" },
  { id: "sweets", name: "मिठाई", nameEn: "Sweets" },
  { id: "honey", name: "शहद", nameEn: "Honey" },
  { id: "ghee", name: "शुद्ध घी", nameEn: "Pure Ghee" },
  { id: "snacks", name: "नाश्ता", nameEn: "Snacks" },
  { id: "beverages", name: "पेय पदार्थ", nameEn: "Beverages" },
  { id: "icecream", name: "आइसक्रीम", nameEn: "Ice Creams" },
];

// Reviews
export const reviews = [
  { name: "Rajesh Kumar", rating: 5, text: "Best peda mahaprasad! Pure ghee aroma and perfect sweetness. Jai Baba Baidyanath!", city: "Deoghar", product: "Peda Mahaprasad" },
  { name: "Priya Sharma", rating: 5, text: "Kaju barfi melts in mouth. Premium quality indeed!", city: "Patna", product: "Kaju Barfi" },
  { name: "Amit Singh", rating: 5, text: "Fresh dahi is amazing! Perfect for our puja rituals.", city: "Ranchi", product: "Dahi" },
  { name: "Sunita Devi", rating: 5, text: "Rasgulla is so soft and spongy. Best I've had!", city: "Kolkata", product: "Rasgulla" },
  { name: "Vikram Mishra", rating: 5, text: "Motichur ladoo is perfect for celebrations. Authentic taste!", city: "Varanasi", product: "Motichur Ladoo" },
  { name: "Anita Gupta", rating: 5, text: "Ghar ka shuddh ghee has authentic aroma. Bilona method!", city: "Delhi", product: "Ghee" },
  { name: "Rohit Tiwari", rating: 4, text: "Samosa with chutney is perfect evening snack!", city: "Gaya", product: "Samosa" },
  { name: "Meera Jha", rating: 5, text: "Jalebi is crispy and syrupy. Best served hot!", city: "Jamshedpur", product: "Jalebi" },
  { name: "Deepak Pandey", rating: 5, text: "Ordered mahaprasad for Baidyanath darshan. Divine!", city: "Mumbai", product: "Peda Mahaprasad" },
  { name: "Kavita Singh", rating: 5, text: "Subah ka nashta is perfect - kachori with sabji!", city: "Bangalore", product: "Nashta" },
  { name: "Sanjay Kumar", rating: 4, text: "Good packaging, fast delivery. Sweets are fresh.", city: "Bhagalpur", product: "Ladoo" },
  { name: "Pooja Verma", rating: 5, text: "Pure honey is delicious and natural taste!", city: "Hyderabad", product: "Honey" },
  { name: "Ramesh Prasad", rating: 5, text: "Best sweets in Deoghar! Have been buying for years.", city: "Deoghar", product: "Sweets" },
  { name: "Neha Agarwal", rating: 5, text: "Doda barfi is rich and delicious. Must try!", city: "Pune", product: "Doda Barfi" },
  { name: "Arun Sharma", rating: 5, text: "Fresh paneer is soft and tasty. Great quality!", city: "Chennai", product: "Paneer" },
  { name: "Rekha Devi", rating: 4, text: "All sweets are fresh and tasty. Will order again.", city: "Dhanbad", product: "Sweets" },
  { name: "Mahesh Yadav", rating: 5, text: "Ordered for wedding, everyone loved it!", city: "Lucknow", product: "Kaju Barfi" },
  { name: "Smita Roy", rating: 5, text: "Raj Bhog is royal! Perfect for special occasions.", city: "Siliguri", product: "Raj Bhog" },
  { name: "Pravin Kumar", rating: 5, text: "Fast delivery to Delhi! Sweets well-packed.", city: "Delhi", product: "Ladoo" },
  { name: "Anjali Mishra", rating: 5, text: "Best mithai shop near Baba Baidyanath temple!", city: "Kolkata", product: "Peda" },
  { name: "Sunil Thakur", rating: 4, text: "Quality sweets at reasonable prices.", city: "Hazaribag", product: "Sweets" },
  { name: "Geeta Devi", rating: 5, text: "Pure and fresh sweets. Jai Baba Baidyanath!", city: "Ranchi", product: "Mahaprasad" },
];

// Weight prices for products with multiple options
export const weightPrices: Record<number, Record<string, number>> = {
  1: { "500g": 70, "1kg": 120 },
  2: { "250g": 120, "500g": 220, "1kg": 400 },
  3: { "250g": 100, "500g": 190, "1kg": 350 },
  4: { "500g": 220, "1kg": 400 },
  5: { "1pc": 10, "6pc": 55, "12pc": 100 },
  6: { "1pc": 10, "6pc": 55, "12pc": 100 },
  7: { "1pc": 10, "6pc": 55, "12pc": 100 },
  8: { "250g": 150, "500g": 280, "1kg": 500 },
  9: { "1pc": 20, "6pc": 110, "12pc": 200 },
  10: { "250g": 280, "500g": 520, "1kg": 950 },
  11: { "250g": 150, "500g": 280, "1kg": 500 },
  12: { "250g": 100, "500g": 180, "1kg": 340 },
  13: { "250g": 100, "500g": 180, "1kg": 340 },
  14: { "250g": 120, "500g": 220, "1kg": 400 },
  15: { "250g": 150, "500g": 280, "1kg": 500 },
  16: { "1pc": 15, "6pc": 80, "700g": 700 },
  17: { "1pc": 20, "6pc": 110, "750g": 750 },
  18: { "1pc": 15, "6pc": 80, "600g": 600 },
  19: { "250g": 150, "500g": 280, "1kg": 500 },
  20: { "1pc": 20, "6pc": 110 },
  21: { "1pc": 20, "6pc": 110 },
  22: { "1pc": 20, "6pc": 110 },
  23: { "1pc": 20, "6pc": 110 },
  24: { "250g": 185, "500g": 350, "1kg": 650 },
  25: { "500g": 600, "1kg": 1135 },
  26: { "1pc": 10, "3pc": 28, "6pc": 55 },
  27: { "1set": 30, "2set": 55, "3set": 80 },
  28: { "1pack": 10, "3pack": 28, "5pack": 45 },
};

// Indian States and Cities Data
export const indianStates = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan",
  "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh",
  "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands",
  "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu", "Jammu and Kashmir",
  "Ladakh", "Lakshadweep", "Puducherry"
];

export const citiesByState: Record<string, string[]> = {
  "Jharkhand": ["Deoghar", "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribag", "Giridih", "Ramgarh", "Palamu", "Dumka", "Godda", "Sahebganj", "Pakur", "Jamtara", "Koderma", "Chatra", "Garhwa", "Latehar", "Simdega", "Lohardaga", "Gumla", "Khunti", "Seraikela"],
  "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Bihar Sharif", "Arrah", "Begusarai", "Katihar", "Munger", "Saharsa", "Sasaram", "Hajipur", "Dehri", "Bettiah", "Motihari", "Chapra", "Samastipur", "Bagaha", "Siwan", "Jehanabad", "Aurangabad"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bardhaman", "Malda", "Baharampur", "Habra", "Kharagpur", "Shantipur", "Dankuni", "Darjeeling", "Ranaghat", "Haldia", "Krishnanagar", "Naihati", "Bangaon", "Medinipur", "Nabadwip", "Kulti", "Basirhat", "Cooch Behar"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Meerut", "Varanasi", "Prayagraj", "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", "Noida", "Firozabad", "Jhansi", "Muzaffarnagar", "Mathura", "Shahjahanpur", "Bijnor", "Rampur", "Etawah", "Mirzapur", "Sultanpur", "Faizabad", "Ayodhya"],
  "Delhi": ["New Delhi", "Central Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "North East Delhi", "South West Delhi", "North West Delhi", "Shahdara", "Dwarka", "Rohini", "Janakpuri", "Pitampura", "Vasant Kunj", "Karol Bagh", "Lajpat Nagar", "Saket", "Hauz Khas", "Connaught Place"],
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Navi Mumbai", "Sangli", "Malegaon", "Jalgaon", "Akola", "Latur", "Dhule", "Ahmednagar", "Chandrapur", "Parbhani", "Jalna", "Bhiwandi", "Amravati", "Nanded", "Sangamner", "Ratnagiri"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Gandhidham", "Anand", "Navsari", "Morbi", "Nadiad", "Surendranadir", "Bharuch", "Mehsana", "Bhuj", "Porbandar", "Palanpur", "Valsad", "Vapi", "Veraval", "Kalol"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Alwar", "Bharatpur", "Pali", "Sikar", "Ganganagar", "Bhilwara", "Sri Ganganagar", "Churu", "Barmer", "Jhalawar", "Jhunjhunu", "Dausa", "Hanumangarh", "Nagaur", "Tonk", "Sawai Madhopur"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa", "Satna", "Ratlam", "Bhind", "Morena", "Betul", "Shivpuri", "Chhindwara", "Vidisha", "Balaghat", "Khandwa", "Khargone", "Sehore", "Damoh", "Katni", "Chhatarpur", "Tikamgarh"],
  "Karnataka": ["Bangalore", "Hubli", "Mysore", "Mangalore", "Gulbarga", "Belgaum", "Davanagere", "Bellary", "Vijayapura", "Shimoga", "Tumkur", "Raichur", "Bidar", "Hassan", "Mandya", "Udupi", "Bagalkot", "Haveri", "Kolar", "Chitradurga", "Koppal", "Chikmagalur", "Dharwad"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Tiruppur", "Erode", "Vellore", "Thoothukudi", "Dindigul", "Thanjavur", "Nagercoil", "Sivakasi", "Cuddalore", "Kancheepuram", "Karur", "Kumbakonam", "Rajapalayam", "Pudukkottai", "Hosur", "Karaikudi", "Ooty"],
  "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Secunderabad", "Mahbubnagar", "Siddipet", "Nalgonda", "Adilabad", "Suryapet", "Miryalaguda", "Jagtial", "Nirmal", "Kamareddy", "Mancherial", "Wanaparthy", "Sangareddy", "Medak", "Bhongir"],
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati", "Kakinada", "Rajahmundry", "Eluru", "Ongole", "Anantapur", "Kadapa", "Machilipatnam", "Tenali", "Proddatur", "Chittoor", "Hindupur", "Srikakulam", "Bhimavaram", "Gudivada"],
  "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur", "Palakkad", "Alappuzha", "Kannur", "Kottayam", "Kasaragod", "Malappuram", "Pathanamthitta", "Idukki", "Wayanad", "Changanassery", "Thalassery", "Ponnani", "Manjeri", "Koyilandy", "Neyyattinkara"],
  "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Hoshiarpur", "Batala", "Pathankot", "Moga", "Abohar", "Ferozepur", "Fazilka", "Malerkotla", "Kapurthala", "Kotkapura", "Muktsar", "Rajpura", "Sangrur", "Sunam"],
  "Haryana": ["Faridabad", "Gurugram", "Panipat", "Ambala", "Karnal", "Rohtak", "Hisar", "Sonipat", "Yamunanagar", "Kurukshetra", "Sirsa", "Bahadurgarh", "Jind", "Rewari", "Palwal", "Kaithal", "Bhiwani", "Narnaul", "Panchkula", "Tohana"],
  "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Roorkee", "Haldwani", "Rudrapur", "Kashipur", "Nainital", "Mussoorie", "Almora", "Pithoragarh", "Uttarkashi", "Tehri", "Chamoli", "Ranikhet", "Kotdwar", "Ramnagar", "Lansdowne", "Srinagar"],
  "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Solan", "Mandi", "Kullu", "Kangra", "Palampur", "Una", "Hamirpur", "Bilaspur", "Chamba", "Kalka", "Parwanoo", "Nahan", "Sundernagar", "Nurpur", "Baddi", "Paonta Sahib", "Dalhousie"],
  "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Bhadrak", "Baripada", "Jharsuguda", "Jeypore", "Bolangir", "Angul", "Dhenkanal", "Jajpur", "Kendrapara", "Koraput", "Nayagarh", "Phulbani", "Paradip"],
  "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Jagdalpur", "Raigarh", "Ambikapur", "Mahasamund", "Dhamtari", "Chirmiri", "Kanker", "Kabirdham", "Janjgir", "Jashpur", "Sukma", "Dantewada", "Narayanpur"],
  "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon", "Dhubri", "Goalpara", "Barpeta", "Sivasagar", "Sonitpur", "Cachar", "Karimganj", "Hailakandi", "Dhemaji", "Lakhimpur", "Kokrajhar", "Nalbari"],
  "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Bicholim", "Sanvordem", "Quepem", "Curchorem", "Canacona", "Pernem", "Sanguem", "Valpoi", "Cuncolim", "Aldona"],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailasahar", "Khowai", "Belonia", "Ambassa", "Kamalpur", "Kunjaban", "Teliamura", "Sonamura", "Sabroom", "Bishalgarh", "Ranirbazar", "Jirania"],
  "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Kakching", "Ukhrul", "Senapati", "Tamenglong", "Chandel", "Jiribam", "Noney", "Kangpokpi", "Tengnoupal", "Kamjong", "Pherzawl"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongpoh", "Williamnagar", "Baghmara", "Nongstoin", "Mairang", "Resubelpara", "Khliehriat", "Ampati", "Mawsynram", "Cherrapunji", "Dawki"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Mon", "Zunheboto", "Phek", "Kiphire", "Longleng", "Peren", "Shamator", "Tseminyu", "Noklak", "Chumoukedima"],
  "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib", "Saiha", "Lawngtlai", "Mamit", "Saitual", "Hnahthial", "Tlabung", "Vairengte", "Bairabi"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Bomdila", "Aalo", "Tezu", "Daporijo", "Roing", "Yingkiong", "Seppa", "Khonsa", "Changlang", "Longding"],
  "Sikkim": ["Gangtok", "Namchi", "Pelling", "Geyzing", "Mangan", "Jorethang", "Rangpo", "Singtam", "Ravangla", "Lachung", "Lachen", "Pakyong", "Soreng", "Dentam"],
  "Andaman and Nicobar Islands": ["Port Blair", "Havelock Island", "Neil Island", "Diglipur", "Mayabunder", "Rangat", "Hut Bay", "Car Nicobar", "Campbell Bay"],
  "Chandigarh": ["Chandigarh", "Mani Majra", "Sector 17", "Sector 22", "Sector 35", "Sector 43", "Sector 20", "Sector 21", "Sector 34", "Mohali"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Silvassa", "Daman", "Diu", "Dadra", "Nagar Haveli", "Bhilad"],
  "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Sopore", "Kathua", "Udhampur", "Punch", "Rajouri", "Kupwara", "Doda", "Kishtwar", "Ramban", "Reasi", "Shopian", "Kulgam", "Ganderbal", "Bandipora", "Pulwama", "Budgam"],
  "Ladakh": ["Leh", "Kargil", "Drass", "Zanskar", "Nubra", "Changthang"],
  "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy", "Amini", "Andrott", "Kalpeni", "Kiltan", "Chetlat", "Kadmat", "Bitra"],
  "Puducherry": ["Puducherry", "Karaikal", "Mahe", "Yanam", "Villianur", "Ozhukarai", "Ariyankuppam", "Kurumbapet", "Kalapet", "Lawspet"]
};

// Order tracking statuses
export const orderStatuses = [
  { id: 1, name: "Order Placed", icon: "CheckCircle2", description: "Your order has been placed successfully" },
  { id: 2, name: "Confirmed", icon: "CheckCircle2", description: "Order confirmed by Madhuram Sweets" },
  { id: 3, name: "Preparing", icon: "Timer", description: "Your sweets are being prepared fresh" },
  { id: 4, name: "Ready for Dispatch", icon: "Package", description: "Order is packed and ready" },
  { id: 5, name: "Out for Delivery", icon: "Truck", description: "Order is on the way" },
  { id: 6, name: "Delivered", icon: "MapPinned", description: "Order delivered successfully" },
];

// Business Info - Updated with correct address and emails
export const businessInfo = {
  name: "Madhuram Sweets",
  tagline: "Pure & Sure",
  subHeader: "Jyotirling Baba Baidyanath Dham ka Mahaprasad",
  hindiTagline: "हमारी मिठाई में बस एक चीज़ है - प्यार और शुद्धता!",
  phone: "07710084997",
  whatsapp: "917710084997",
  emails: ["vikas9719@gmail.com", "bababaijnath@MadhuraMsweets.com"],
  website: "madhuramsweets.in",
  address: "HadHadiya Pool, Deoghar College Road, Deoghar, Jharkhand – 814112",
  fullAddress: "Near HadHadiya Pool, Deoghar College Road, Shivganga Muhalla, Deoghar, Jharkhand – 814112",
  mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3634.4567!2d86.6979!3d24.4853!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39f128b9b9b9b9b9%3A0x1234567890!2sHadHadiya%20Pool%2C%20Deoghar%20College%20Road%2C%20Deoghar%2C%20Jharkhand!5e0!3m2!1sen!2sin!4v1234567890",
  mapLink: "https://www.google.com/maps/search/?api=1&query=HadHadiya+Pool+Deoghar+College+Road+Deoghar+Jharkhand",
  timings: {
    weekdays: "8:00 AM - 9:00 PM",
    sunday: "9:00 AM - 8:00 PM",
  },
  social: {
    facebook: "https://facebook.com/madhuramsweets",
    instagram: "https://instagram.com/madhuramsweets",
    whatsapp: "https://wa.me/917710084997",
  },
};

export const getBadgeStyle = (type: string): string => {
  switch (type) {
    case "divine":
      return "bg-gradient-to-r from-amber-500 to-yellow-400 text-amber-900";
    case "temple":
      return "bg-gradient-to-r from-red-800 to-red-600 text-white";
    case "gold":
      return "bg-gradient-to-r from-yellow-500 to-amber-500 text-white";
    case "premium":
      return "bg-gradient-to-r from-purple-700 to-purple-500 text-white";
    case "fresh":
      return "bg-gradient-to-r from-green-600 to-green-500 text-white";
    case "vrat":
      return "bg-gradient-to-r from-orange-600 to-amber-500 text-white";
    case "traditional":
      return "bg-gradient-to-r from-orange-700 to-orange-500 text-white";
    case "popular":
      return "bg-gradient-to-r from-pink-600 to-rose-500 text-white";
    case "organic":
      return "bg-gradient-to-r from-emerald-600 to-green-500 text-white";
    case "pure":
      return "bg-gradient-to-r from-amber-600 to-yellow-500 text-white";
    default:
      return "bg-gradient-to-r from-orange-500 to-amber-500 text-white";
  }
};

// Indian Languages for translation
export const indianLanguages = [
  { code: "hi", name: "हिंदी", englishName: "Hindi" },
  { code: "bn", name: "বাংলা", englishName: "Bengali" },
  { code: "te", name: "తెలుగు", englishName: "Telugu" },
  { code: "mr", name: "मराठी", englishName: "Marathi" },
  { code: "ta", name: "தமிழ்", englishName: "Tamil" },
  { code: "gu", name: "ગુજરાતી", englishName: "Gujarati" },
  { code: "kn", name: "ಕನ್ನಡ", englishName: "Kannada" },
  { code: "ml", name: "മലയാളം", englishName: "Malayalam" },
  { code: "pa", name: "ਪੰਜਾਬੀ", englishName: "Punjabi" },
  { code: "or", name: "ଓଡ଼ିଆ", englishName: "Odia" },
  { code: "as", name: "অসমীয়া", englishName: "Assamese" },
  { code: "ur", name: "اردو", englishName: "Urdu" },
  { code: "en", name: "English", englishName: "English" },
];
